name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'

jobs:
  nixpkgs-fmt:
    runs-on: ubuntu-latest
    env:
      NIX_PATH: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/master.tar.gz"
    steps:
    - uses: cachix/install-nix-action@v8
    - uses: actions/checkout@v1
    - name: Check format
      run: ./check-fmt

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        nixpkgs_version: ["20.03", "master"]
        # os: [ubuntu-latest, macos-latest]
    env:
      NIX_PATH: "nixpkgs=https://github.com/NixOS/nixpkgs/archive/${{ matrix.nixpgs_version }}.tar.gz"
    steps:
    - uses: cachix/install-nix-action@v8
    - uses: actions/checkout@v1
    - uses: cachix/cachix-action@v5
      with:
        name: poetry2nix
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        file: tests/default.nix
